
INSERT INTO T_ARTIST(NAME) VALUES ('EMRE KURU');
INSERT INTO T_ARTIST(NAME) VALUES ('DENIZ SENER');
INSERT INTO T_ALBUM(NAME,ARTIST_ID) VALUES ('FIRST ALBUM',1);
INSERT INTO  T_SONG(NAME,LENGTH,ALBUM_ID,ARTIST_ID) VALUES ('My Song',100,1,1);
INSERT INTO  T_SONG(NAME,LENGTH,ALBUM_ID,ARTIST_ID) VALUES ('Second Song',100,1,1);
